[package]
name = "tmp"
description.workspace = true
documentation.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
